/**
 * At Long Last - Activity Registry
 * Drop this into src/features/session/activityRegistry.ts
 * 45 activities across tender / playful / spicy
 */

export type Vibe = 'tender' | 'playful' | 'spicy';
export type ActivityType = 'prompt' | 'ritual' | 'journal';

export interface Activity {
  id: string;
  vibe: Vibe;
  type: ActivityType;
  intensity: 1 | 2 | 3;
  title: string;
  prompt: string;
  description: string;
  durationSec: number;
  skippable: boolean;
  savesToJournal: boolean;
  tags: string[];
}

export const ACTIVITIES: Activity[] = [
  // TENDER - 15
  {
    id: 'comfort-menu',
    vibe: 'tender',
    type: 'prompt',
    intensity: 1,
    title: 'Comfort Menu',
    prompt: "When I'm overwhelmed, what actually helps is...",
    description: 'Build your personal comfort cheat sheet for each other.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['support', 'needs', 'cozy']
  },
  {
    id: 'small-mercies',
    vibe: 'tender',
    type: 'prompt',
    intensity: 1,
    title: 'Small Mercies',
    prompt: 'Name one tiny thing I did this week you appreciated that I probably thought you did not notice.',
    description: 'Catch the invisible kindness.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['gratitude', 'noticing']
  },
  {
    id: 'weather-report',
    vibe: 'tender',
    type: 'prompt',
    intensity: 1,
    title: 'Weather Report',
    prompt: 'My internal weather today is sunny, foggy, stormy, or clear because...',
    description: 'No fixing, just reporting.',
    durationSec: 60,
    skippable: true,
    savesToJournal: false,
    tags: ['check-in', 'emotional']
  },
  {
    id: 'receipts',
    vibe: 'tender',
    type: 'prompt',
    intensity: 1,
    title: 'Receipts',
    prompt: 'Find the oldest photo of us on your phone. What do you remember about that day that the photo does not show?',
    description: 'Race to find it, then story swap.',
    durationSec: 120,
    skippable: true,
    savesToJournal: true,
    tags: ['memory', 'photo']
  },
  {
    id: 'future-artifact',
    vibe: 'tender',
    type: 'journal',
    intensity: 2,
    title: 'Future Artifact',
    prompt: 'If someone found a box of our stuff 50 years from now, what 3 things should be in it?',
    description: 'Build your legacy box.',
    durationSec: 120,
    skippable: true,
    savesToJournal: true,
    tags: ['future', 'legacy']
  },
  {
    id: 'postcard-next-year',
    vibe: 'tender',
    type: 'journal',
    intensity: 2,
    title: 'Postcard From Next Year',
    prompt: 'Write a 2-sentence note your future selves will open in 12 months. Start with "Remember when we..."',
    description: 'Saves to journalEntries with open date +12 months.',
    durationSec: 120,
    skippable: true,
    savesToJournal: true,
    tags: ['future', 'time-capsule']
  },
  {
    id: 'translation',
    vibe: 'tender',
    type: 'prompt',
    intensity: 1,
    title: 'Translation',
    prompt: 'How I say I love you without saying it is...',
    description: 'Decode your love language actions.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['love-language']
  },
  {
    id: 'map-pin-wish',
    vibe: 'tender',
    type: 'ritual',
    intensity: 1,
    title: 'Map Pin',
    prompt: 'Drop a pin where you wish you were together right now. The other guesses why.',
    description: 'Uses map placeholder or text description.',
    durationSec: 90,
    skippable: true,
    savesToJournal: false,
    tags: ['longing', 'future-date']
  },
  {
    id: 'director-commentary',
    vibe: 'tender',
    type: 'prompt',
    intensity: 1,
    title: "Director's Commentary",
    prompt: 'Describe the day we met like it is a movie trailer.',
    description: 'Dramatic retelling.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['story', 'origin']
  },
  {
    id: 'house-rules',
    vibe: 'tender',
    type: 'prompt',
    intensity: 1,
    title: 'House Rules',
    prompt: 'Invent one ridiculous rule for our future house together.',
    description: 'World building for two.',
    durationSec: 60,
    skippable: true,
    savesToJournal: true,
    tags: ['future', 'playful-tender']
  },
  {
    id: 'growth-ring',
    vibe: 'tender',
    type: 'journal',
    intensity: 2,
    title: 'Growth Ring',
    prompt: 'What is something hard from 6 months ago that feels lighter now because we handled it together?',
    description: 'Notice growth.',
    durationSec: 120,
    skippable: true,
    savesToJournal: true,
    tags: ['growth', 'resilience']
  },
  {
    id: 'anchor-memory',
    vibe: 'tender',
    type: 'prompt',
    intensity: 2,
    title: 'Anchor Memory',
    prompt: 'What is a memory of us you go to when you need to feel grounded?',
    description: 'Share your anchor.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['memory', 'grounding']
  },
  {
    id: 'unsent-draft',
    vibe: 'tender',
    type: 'prompt',
    intensity: 2,
    title: 'Unsent Draft',
    prompt: 'What text did you almost send me this week and delete?',
    description: 'Say the quiet part.',
    durationSec: 90,
    skippable: true,
    savesToJournal: false,
    tags: ['vulnerability']
  },
  {
    id: 'gratitude-snapshot',
    vibe: 'tender',
    type: 'ritual',
    intensity: 1,
    title: 'Gratitude Snapshot',
    prompt: 'Both take a photo of your current view and caption it "this is where I love you from today".',
    description: 'Async photo ritual.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['photo', 'gratitude']
  },
  {
    id: 'shared-seed',
    vibe: 'tender',
    type: 'ritual',
    intensity: 1,
    title: 'Shared Seed',
    prompt: 'A plant on the board grows only if you both water it today. Water it?',
    description: 'Daily co-care ritual. No death, just droop.',
    durationSec: 30,
    skippable: true,
    savesToJournal: false,
    tags: ['daily', 'co-care']
  },

  // PLAYFUL - 15
  {
    id: 'cursed-date-12',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Cursed Date',
    prompt: 'You have $12 and a gas station. Plan our best date possible.',
    description: 'Forced creativity.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['funny', 'creativity']
  },
  {
    id: 'yelp-review',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Yelp Review',
    prompt: 'Write a 5-star Yelp review for your partner as if they are a restaurant.',
    description: 'Overly specific praise.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['funny', 'compliment']
  },
  {
    id: 'build-a-cult',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Build-A-Cult',
    prompt: 'Invent a cult based on our weirdest shared habit. What is the uniform? The motto?',
    description: 'Lore building.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['lore', 'funny']
  },
  {
    id: 'lore-drop',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Lore Drop',
    prompt: 'What is the official origin story of our dumbest inside joke? Make it epic.',
    description: 'Canonize the joke.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['inside-joke', 'story']
  },
  {
    id: 'two-truths-one-dream',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Two Truths and a Dream',
    prompt: 'Two true memories, one dream memory you wish we had. Partner guesses the dream.',
    description: 'Twist on classic game.',
    durationSec: 120,
    skippable: true,
    savesToJournal: false,
    tags: ['game', 'memory']
  },
  {
    id: 'alternate-job',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Alternate Universe Job',
    prompt: 'In another life, I think you would be an amazing... because...',
    description: 'See them differently.',
    durationSec: 60,
    skippable: true,
    savesToJournal: false,
    tags: ['imagination']
  },
  {
    id: 'apocalypse-role',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Apocalypse Role',
    prompt: 'Zombie apocalypse. What is my job in our duo and what is yours? No, you cannot both be the chef.',
    description: 'Assign survival roles.',
    durationSec: 90,
    skippable: true,
    savesToJournal: false,
    tags: ['funny', 'role']
  },
  {
    id: 'pet-peeve-love-letter',
    vibe: 'playful',
    type: 'prompt',
    intensity: 2,
    title: 'Pet Peeve Love Letter',
    prompt: 'Write a love letter to my most annoying cute habit.',
    description: 'Roast with love.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['roast', 'affection']
  },
  {
    id: 'conspiracy-us',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Conspiracy: Us',
    prompt: 'What is our wildest conspiracy theory that is actually true? Like "we were meant to meet because..."',
    description: 'Romantic conspiracies.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['romantic-funny']
  },
  {
    id: 'wikipedia-us',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Wikipedia: Us',
    prompt: 'Write the intro paragraph to our Wikipedia page.',
    description: 'Legacy but funny.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['legacy', 'funny']
  },
  {
    id: 'theme-song',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Theme Song',
    prompt: 'What is our current theme song? Not our song, our sitcom theme song this week.',
    description: 'Quick music share.',
    durationSec: 60,
    skippable: true,
    savesToJournal: false,
    tags: ['music']
  },
  {
    id: 'bad-advice',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Bad Advice',
    prompt: 'Give me terrible advice for a problem I have this week. The worse the better.',
    description: 'Reverse support.',
    durationSec: 60,
    skippable: true,
    savesToJournal: false,
    tags: ['funny', 'support']
  },
  {
    id: 'villain-origin',
    vibe: 'playful',
    type: 'prompt',
    intensity: 1,
    title: 'Villain Origin',
    prompt: 'What mundane event would turn me into a supervillain? Narrate my origin.',
    description: 'Dramatic backstory.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['funny', 'story']
  },
  {
    id: 'nudge-wars',
    vibe: 'playful',
    type: 'ritual',
    intensity: 1,
    title: 'Nudge Wars',
    prompt: 'Leave a surprise on their board: rubber duck, disco ball, cactus, or love note?',
    description: 'Async board decoration ritual.',
    durationSec: 20,
    skippable: true,
    savesToJournal: false,
    tags: ['ritual', 'async']
  },
  {
    id: 'sound-capsule',
    vibe: 'playful',
    type: 'ritual',
    intensity: 1,
    title: 'Sound Capsule',
    prompt: 'Leave a 7-second sound on this tile for your partner to find on their next roll.',
    description: 'Voice, laugh, weird noise.',
    durationSec: 30,
    skippable: true,
    savesToJournal: false,
    tags: ['audio', 'async']
  },

  // SPICY - 15 (tasteful, romantic, opt-in)
  {
    id: 'replay-favorite-kiss',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 1,
    title: 'Replay',
    prompt: 'My favorite kiss was not the most romantic one, it was the one when...',
    description: 'Memory that is intimate without being explicit.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['romantic', 'memory']
  },
  {
    id: 'wanted-list',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 1,
    title: 'Wanted List',
    prompt: 'One non-physical thing you do that instantly makes me feel wanted is...',
    description: 'Focus on emotional desire.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['desire', 'emotional']
  },
  {
    id: 'slow-morning',
    vibe: 'spicy',
    type: 'journal',
    intensity: 2,
    title: 'Slow Morning',
    prompt: 'Describe our ideal slow morning together, hour by hour, from waking up to getting coffee.',
    description: 'Cozy intimacy visualization.',
    durationSec: 120,
    skippable: true,
    savesToJournal: true,
    tags: ['intimacy', 'future']
  },
  {
    id: 'confidence-fit',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 1,
    title: 'Confidence Fit',
    prompt: 'What is an outfit you wear that makes YOU feel amazing? Describe it so I can picture you.',
    description: 'Celebrate confidence.',
    durationSec: 60,
    skippable: true,
    savesToJournal: false,
    tags: ['confidence', 'flirty']
  },
  {
    id: 'whisper-line',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 2,
    title: 'Whisper Line',
    prompt: 'If you could teleport next to me for 10 seconds right now, what would you whisper?',
    description: 'Short and sweet.',
    durationSec: 60,
    skippable: true,
    savesToJournal: false,
    tags: ['flirty', 'longing']
  },
  {
    id: 'scent-memory',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 1,
    title: 'Scent Memory',
    prompt: 'What scent instantly reminds you of me or us?',
    description: 'Sensory memory.',
    durationSec: 60,
    skippable: true,
    savesToJournal: true,
    tags: ['sensory', 'memory']
  },
  {
    id: 'favorite-way-held',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 2,
    title: 'How I Like To Be Held',
    prompt: 'My favorite way to be held when I am tired vs when I am happy is...',
    description: 'Non-explicit touch preferences.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['touch', 'comfort']
  },
  {
    id: 'look-you-love',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 1,
    title: 'That Look',
    prompt: 'Describe a look on my face that you love and when you usually see it.',
    description: 'Noticing details.',
    durationSec: 60,
    skippable: true,
    savesToJournal: true,
    tags: ['noticing', 'romantic']
  },
  {
    id: 'flirt-resume',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 2,
    title: 'Flirt Resume',
    prompt: 'What is your go-to move when you are trying to make me blush? Is it working right now?',
    description: 'Playful self-awareness.',
    durationSec: 60,
    skippable: true,
    savesToJournal: false,
    tags: ['flirty', 'playful-spicy']
  },
  {
    id: 'what-miss-today',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 2,
    title: 'What I Miss Today',
    prompt: 'The specific thing I miss about being next to you today is...',
    description: 'Daily longing prompt.',
    durationSec: 60,
    skippable: true,
    savesToJournal: false,
    tags: ['longing', 'daily']
  },
  {
    id: 'date-that-never-ends',
    vibe: 'spicy',
    type: 'journal',
    intensity: 2,
    title: 'Date That Never Ends',
    prompt: 'Design a date that has no end time, no phones, no plans. Where does it start?',
    description: 'Fantasy date building.',
    durationSec: 120,
    skippable: true,
    savesToJournal: true,
    tags: ['fantasy-date']
  },
  {
    id: 'secret-admiration',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 1,
    title: 'Secret Admiration',
    prompt: 'Something I find attractive about you that I have never said out loud is...',
    description: 'Low-pressure compliment.',
    durationSec: 90,
    skippable: true,
    savesToJournal: true,
    tags: ['admiration']
  },
  {
    id: 'after-hours-tile',
    vibe: 'spicy',
    type: 'ritual',
    intensity: 2,
    title: 'After Hours',
    prompt: 'This tile only glows after 9pm for both of you. Leave a photo of your eyes, your smile, or your hand right now.',
    description: 'Time-gated intimacy ritual.',
    durationSec: 30,
    skippable: true,
    savesToJournal: true,
    tags: ['ritual', 'time-gated', 'photo']
  },
  {
    id: 'landing-lights',
    vibe: 'spicy',
    type: 'ritual',
    intensity: 1,
    title: 'Landing Lights',
    prompt: 'End-of-day ritual: land on the home tile together. 3 nights in a row unlocks a love note.',
    description: 'Co-sleep ritual for remote couples.',
    durationSec: 20,
    skippable: true,
    savesToJournal: false,
    tags: ['ritual', 'nightly']
  },
  {
    id: 'rewind-touch',
    vibe: 'spicy',
    type: 'prompt',
    intensity: 2,
    title: 'Rewind',
    prompt: 'What is a tiny, non-sexual touch from us that lives rent-free in your head? Forehead kiss, hand squeeze, etc.',
    description: 'Celebrate small touch.',
    durationSec: 60,
    skippable: true,
    savesToJournal: true,
    tags: ['touch', 'memory']
  }
];
